app/account/urls.py
"""Url mappings for the user API"""

from django.urls import path
from .api_views import CreateUserView, CreateTokenView

app_name = "account"

urlpatterns = [
    path("create/", CreateUserView.as_view(), name="create"),
    path("token/", CreateTokenView.as_view(), name="token")
]

app/core/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("costs/", include("costs.urls", namespace="costs")),
    path("account/", include("account.urls", namespace="account")),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

app/costs/urls.py
from django.urls import path
from .views import listView, detailedListView

app_name = "costs"

urlpatterns = [
    path("<str:requested_year>/", listView, name="months-list"),
    path("<str:requested_year>/<str:requested_month>/", detailedListView, name="detailed-list"),
]

app/account/models.py
"""Database models"""
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)


class UserManager(BaseUserManager):
    """create save and return new user"""

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("User must have email address.")
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """User in system"""

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"

app/costs/models.py
from django.db import models
from account.models import User
from django.urls import reverse
from django.utils.timezone import now


class FixedCosts(models.Model):
    user = models.ForeignKey(User, related_name="fixed_costs", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    sume = models.DecimalField(max_digits=11, decimal_places=2)
    notes = models.CharField(max_length=300, blank=True)

    class Meta:
        verbose_name_plural = "Fixed Costs"
        ordering = ["-sume"]

    def __str__(self) -> str:
        return self.title

    # def get_absolute_url(self):
    #     return reverse("model_detail", kwargs={"pk": self.pk})


class VariableCosts(models.Model):
    user = models.ForeignKey(
        User, related_name="variable_costs", on_delete=models.CASCADE
    )
    title = models.CharField(max_length=200)
    sume = models.DecimalField(max_digits=11, decimal_places=2)
    notes = models.CharField(max_length=300, blank=True)
    date = models.DateField(default=now)

    class Meta:
        verbose_name_plural = "Variable Costs"
        ordering = ["date"]

    def __str__(self) -> str:
        return self.title


class Income(models.Model):
    user = models.ForeignKey(User, related_name="income", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    sume = models.DecimalField(max_digits=11, decimal_places=2)
    notes = models.CharField(max_length=300, blank=True)
    date = models.DateField(default=now)

    class Meta:
        verbose_name_plural = "Income"
        ordering = ["date"]

    def __str__(self) -> str:
        return self.title

    # def get_absolute_url(self):
    #     return reverse("model_detail", kwargs={"pk": self.pk})

app/account/views.py
from django.shortcuts import render

# Create your views here.

app/costs/views.py
from calendar import month
from django.shortcuts import render
from .models import Income, FixedCosts, VariableCosts
from django.db.models import DateField
import calendar
from datetime import datetime


def listView(request, requested_year):
    distinct_months = (
        VariableCosts.objects.filter(date__year=requested_year)
        .values_list("date__month", flat=True)
        .distinct()
        .order_by("date__month")
    )
    distinct_months = [
        calendar.month_name[month_number] for month_number in distinct_months
    ]

    return render(
        request,
        "costs/months-list.html",
        context={"months": distinct_months, "requested_year": requested_year},
    )


def detailedListView(request, requested_year, requested_month):
    month_number = datetime.strptime(requested_month, "%B").month
    variable_costs = VariableCosts.objects.filter(
        date__year=requested_year, date__month=month_number
    )

    return render(
        request, "costs/month-details.html", context={"variable_costs": variable_costs}
    )

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
              crossorigin="anonymous">
        {% block style %}
        {% endblock style %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'costs:months-list' 2023 %}"> 
                    <img src="{% static 'logo/piggy-bank.png' %}"
                         alt="Logo"
                         width="30"
                         height="24"
                         class="d-inline-block align-text-top">
                    Costly
                </a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link"
                               href="">Go Back</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               href="#"
                               role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">Year</a>
                            <ul class="dropdown-menu">
                                {% for year in years %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'costs:months-list' year %}">{{year}}</a>
                                        
                                    </li>
                                {% endfor %}
                                
                                {% comment %} <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       href="">Remove your order</a>
                                </li> {% endcomment %}
                            </ul>
                        </li>
                    </ul>
                    <a class="btn btn-outline-light me-2"
                       href="">All items</a>
                    <form class="d-flex"
                          role="search"
                          action=""
                          method="GET">
                        {% csrf_token %}
                        <input class="form-control me-2"
                               type="search"
                               placeholder="Search"
                               aria-label="Search"
                               name="query">
                        <button class="btn btn-outline-light" type="submit">Search</button>
                    </form>
                    {% if user.is_authenticated %}
                        <a class="btn btn-outline-light ms-2" href="">Logout</a>
                    {% else %}
                        <a class="btn btn-outline-light ms-2"
                           href="">Login</a>
                        <a class="btn btn-outline-light ms-2" href="">SignUp</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <section class="content_section">
            {% block content %}
            {% endblock content %}
        </section>
        <div class="container">
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top footer-dark">
                <div class="col-md-4 d-flex align-items-center">
                    <a href=""
                       class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                        <img src="{% static 'logo/piggy-bank.png' %}" width="24" height="24"> 
                    </a>
                    <span class="mb-3 mb-md-0 ">&copy; 2023 Pawel Mazurkiewicz</span>
                </div>
                <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3">
                        <a class="text-muted"
                           href="https://www.linkedin.com/in/pawel-mazurkiewicz-906877173/">
                            <img src="{% static 'logo/linkedin.png' %}" width="24" height="24">
                        </a>
                    </li>
                    <li class="ms-3">
                        <a class="text-muted" href="https://github.com/Paul-Mazu">
                            <img src="{% static 'logo/github.png' %}" width="24" height="24">                        </a>
                    </li>
                </ul>
            </footer>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
                crossorigin="anonymous"></script>
    </body>
</html>

app/templates/costs/month-details.html
{% extends '../base.html' %}
{% block title %}Detail page{% endblock title %}
{% block content %}


<table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Title</th>
        <th>Sume</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
        {% for cost in variable_costs %}
            <tr>
                <td>{{ cost.date }}</td>
                <td>{{ cost.title }}</td>
                <td>{{ cost.sume }}</td>
                <td>{{ cost.notes }}</td>
            </tr>
        {% endfor %}
    </tbody>
  </table>



{% endblock content %}

app/templates/costs/months-list.html
{% extends '../base.html' %}
{% block title %}Index Page{% endblock title %}
{% block content %}

    {% for month in months %}

        <p>
            <a href="{% url 'costs:detailed-list' requested_year month %}">{{month}}</a>
            
        </p>
    
    {% endfor %}

{% endblock content %}